var inum = 10;
var strName = 'Dhanashri';
var bData = true;
var anyDataType = 200;
console.log("Number is " + inum);
console.log("my name is  " + strName);
console.log("is it true " + bData);
console.log("any data type " + anyDataType);
anyDataType = "changed to text";
console.log("any data type now is" + anyDataType);
anyDataType = true;
console.log("any data type data now is" + anyDataType);
